# Railway Configuration File
# This file configures your ANT+ Bridge deployment automatically

[build]
# Use Nixpacks builder (Railway's default)
builder = "nixpacks"

# Watch for changes in these file patterns
watchPatterns = [
  "**/*.js",
  "package.json",
  "Procfile",
  "railway.json"
]

# Build command (usually auto-detected)
buildCommand = "npm install"

[deploy]
# Start command for your ANT+ bridge server
startCommand = "node ant-bridge-server.js"

# Restart policy - restart on failure
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

# Health check configuration
healthcheckPath = "/"
healthcheckTimeout = 300

[networking]
# Enable public networking
publicPort = true

[scaling]
# Resource limits for free tier
minReplicas = 1
maxReplicas = 1

[variables]
# Environment variables for Railway deployment
NODE_ENV = "production"
RAILWAY_STATIC_URL = "web-production-f8ebc.up.railway.app"
PLATFORM = "railway"

[regions]
# Deploy to US East region
"us-east1" = { replicas = 1 }
